### ISSUE TITLE
[feature request] onlyProps() Nested properties support

### ISSUE THREAD

**Issue by wujekbogdan** [reactioncommerce/meteor-security#19]
It would be great if onlyProps() supported nested properties. Let's say I have an object containing users data,  but I want to publish only some of them for example nickname, avatar, but hide user ID and user email. 

At the moment I use a workaround - I call this.unset() method in the simpleSchema autoValue() callback.

**Comment by aldeed** [comment]
I agree this would be nice, but since this package is a wrapper for allow/deny and Meteor only gives us "top-level" field names in allow/deny, there's no simple way to do this right now.

**Comment by CaptainN** [comment]
Is this not yet implemented? It seems we could do something similar to the way nested objects are defined in SimpleSchema - something like:

```JavaScript
.exceptProps([
    'nested.prop1', 'nested.prop2'
])
```

Then check for those kinds of queries in the except exceptProps definition?

**Comment by aldeed** [comment]
We can certainly do it by pulling in a ton of modifier-parsing code from SS, but I don't know if it would be a good idea to put that much code in this base package. I think a good solution would be an add-on package that adds `exceptNestedProps` and `onlyNestedProps`.

Or possibly a pkg that overrides/hacks allow/deny to provide detailed field list instead of only top-level fields.

**Comment by vimes1984** [comment]
Where did we get with this? 
I'm looking at a chat room setup Schema where the messages are attached to the room and contributors can add messages but not rooms...

**Comment by CaptainN** [comment]
It's a complex feature to add to a relatively simple library. You can add something to your own toolchain though. Here is what I used on a recent project:

```JavaScript
Security.defineMethod("exceptSubProps", {
    fetch: [],
    transform: null,
    deny: function (type, arg, userId, doc, fieldNames) {
      if (!_.isArray(arg.props)) {
        arg.props = [arg.props];
      }

      fieldNames = fieldNames || _.keys (doc [arg.sub]);

      return _.any(fieldNames, function (fieldName) {
        return _.contains(arg.props, fieldName);
      });
    }
  });
```

use like: 

```JavaScript
.exceptSubProps ({sub: 'parentProp', props: [
   'subProp1', 'subProp2', 'etc',
]})
```

**Comment by vimes1984** [comment]
You sir are a star :D 
Thank you I'll use that if you don't mind!

**Comment by dr-dimitru** [comment]
@CaptainN great, thanks.
But what about more nested levels? Like: `grand.parent.prop`

**Comment by dr-dimitru** [comment]
Found this workaround a better than suggested by @CaptainN , hope someone found this helpful also
```javascript
Security.defineMethod('exceptSubProps', {
  fetch: [],
  transform: null,
  deny: function(type, allowed, userId, doc, fieldNames, modifier) {
    var field, obj, operator, results, value;
    if (!_.isArray(allowed)) {
      allowed = [allowed];
    }
    results = [];
    for (operator in modifier) {
      obj = modifier[operator];
      for (field in obj) {
        value = obj[field];
        results.push(!!~allowed.indexOf(field));
      }
    }
    return !!~results.indexOf(true);
  }
});

Security.defineMethod('onlySubProps', {
  fetch: [],
  transform: null,
  deny: function(type, allowed, userId, doc, fieldNames, modifier) {
    var field, obj, operator, results, value;
    if (!_.isArray(allowed)) {
      allowed = [allowed];
    }
    results = [];
    for (operator in modifier) {
      obj = modifier[operator];
      for (field in obj) {
        value = obj[field];
        results.push(!~allowed.indexOf(field));
      }
    }
    return !!~results.indexOf(true);
  }
});
```

Example usage:
```javascript
Collection.permit('update').exceptSubProps(['parent.nested.field']).apply();
Collection.permit('update').onlySubProps(['nested.field']).apply();
```

**Comment by mymedicalshopper** [comment]
Nice solution @dr-dimitru. It appears that those two functions also work properly for top-level properties, as well, meaning those two functions could be used instead of the normal "exceptProps" and "onlyProps", correct? It appears that way to me and my quick testing says so, too, but looking for a second opinion just to make sure.

**Comment by dr-dimitru** [comment]
@mymedicalshopper actually you're right. But I'll recommend to use both `exceptProps` and `exceptSubProps` (`onlyProps ` and `onlySubProps `) for convention.

Hope @aldeed will use my snippet to provide nested props support to `exceptProps` and `onlyProps`.
Hey, @aldeed I can send a PR, if you agree on this?

**Comment by aldeed** [comment]
@dr-dimitru My only problem with it is that it wouldn't actually fully secure those subprops ("only" might work well enough but "except" would not be secure). For example, you could just get around your check with:

```
update({}, { $set: { 'parent.nested': { field: 5 } } })
```


To do that properly would require a lot of modifier parsing logic, which is why Meteor only deals with top-level props.

My mongo-object npm package actually does a lot of that modifier parsing so possibly we could use that, but it would bloat this core package so it's probably better done as a separate add-on package.

It might also work reasonably well to assume that each ancestor field cannot be set either, but there are probably edge cases. Maybe we could write such a function but have it reject all operators other than $set and $unset, in which case we could make it pretty secure with enough logic.

**Comment by dr-dimitru** [comment]
@aldeed described issue may be easily solved with `objectToDottedString` function, so rules and modifiers will be presented in same way for comparison.

**Comment by aldeed** [comment]
This package is no longer being updated or supported by Reaction.
